title: Paul Karam's Developer Notes
email: paulkaram1989@gmail.com
description: >-
  .NET Consultant, and Mentor sharing practical insights into C#, .NET, software architecture, and modern software engineering.
baseurl: ""
url: ""

theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
author:
  name: Paul Karam
excerpt_separator: <!--more-->

navigation:
  - title: Home
    url: /

  - title: Blog
    url: /posts/

  - title: About
    url: /about/

  - title: Contact
    url: /contact/

google_analytics: G-CF2QZBNZNR

profile_image: /assets/profile_pic.jpg

social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/paul-karam-b10673123/
    icon: linkedin
  - name: X
    url: https://x.com/tiger45_
    icon: x
  - name: Instagram
    url: https://www.instagram.com/tiger45_/
    icon: instagram
  - name: GitHub
    url: https://github.com/tiger4589
    icon: github

emails:
  - name: Personal Email
    address: paulkaram1989@gmail.com
  - name: Work Email
    address: paul.karam@allphi.eu
